version: 0.1
phases:
  install:
#   commands:
#     - sudo amazon-linux-extras install java-openjdk11
#     - sudo yum install java-1.8.0-openjdk
    runtime-versions:
        java: openjdk11
  install:
   commands:
     - echo Entering install phase...
     - wget https://services.gradle.org/distributions/gradle-5.0-bin.zip -P /tmp
     - sudo unzip -d /opt/gradle /tmp/gradle-5.0-bin.zip
     - ls /opt/gradle/gradle-5.0
     - sudo yum install nano
     - sudo nano /etc/profile.d/gradle.sh
     - sudo chmod +x /etc/profile.d/gradle.sh
     - source /etc/profile.d/gradle.sh
     - gradle -v
  build:
    commands:
     - echo Build started on `date`
     - gradlew compile
    commands:
     - gradlew build
     - gradle package
artifacts:
  files:
    - 'helloworld.jar'
