version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_SRC_DIR
      - uServices/hello-world-java/gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - uServices/hello-world-java/build/distributions/*
