
version: 0.2

run-as: ubuntu

phases:
    commands:
      - apt-get install -y gradle
  pre_build:
    run-as: ubuntu
    on-failure: CONTINUE
    commands:
      - gradle clean
  build:
    run-as: ubuntu
    on-failure:  CONTINUE
    commands:
      - gradle build
  post_build:
    run-as: ubuntu
    on-failure:  CONTINUE
    commands:
      - gradle package
artifacts:
  files:
    - target/helloworld.jar
  name: helloworld.jar
  discard-paths: no 
  base-directory: /target
  s3-prefix: bucket-new123456
