version: 0.1

phases:
  install:
    runtime-versions:
        java: correto11
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now
  build:
    commands:
     - echo Build started on `date`
     - gradlew compile
    commands:
     - gradlew build
    commands:
     - gradlew bootjar
artifacts:
  type: zip
  files:
    - 'target/boot.jar'
